using System.Collections;
using System.Collections.Generic;
using System;
using UnityEngine;

public class Tile : MonoBehaviour
{
    public void setCoordText(Tuple<int,int> chID , Tuple<int,int> coords)
    {
        var x = GetComponentInChildren<TextMesh>(true);
        x.text = chID.ToString() + " " +coords.ToString();
        //x.text = chID.ToString() + " " +coords.ToString() +" " + transform.position.ToString();
        //x.text =  coords.ToString();
    }
#region Attributes
    public TileTypes _type; //The type of the tile
    public Building _building; //The building on this tile
    public List<Tile> _neighborTiles; //List of all surrounding tiles. Generated by GameManager
#endregion

#region Enumerations
    public enum TileTypes { Empty, Water, Sand, Grass, Forest, Stone, Mountain }; //Enumeration of all available tile types. Can be addressed from other scripts by calling Tile.Tiletypes
#endregion

    //This class acts as a data container and has no functionality
}
